# Generated by Django 5.0.4 on 2024-05-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0002_productdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='pprice',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
