# Generated by Django 5.0.4 on 2024-05-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0003_alter_productdb_pprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='pprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
